[schema]
version = "0.0.1"

[meta]
document_id = "LLR-DOC-001"
revision = "1"

[[requirements]]
uid = "6d443dd1-7f5c-45a1-85ed-42eab53ab9ee"
id = "llr-example"
title = "Example Implementation Requirement"
owner = "team@example.com"
traces_to = ["0e60162d-bdf5-4320-a735-e4368c4af78e"]
modules = []
derived = false
description = "This is an example low-level requirement."
verification_methods = ["test"]
