//! The internal-command escape hatch for FC-generated commands.
//!
//! [`TrustedInternalCommand`] is a *distinct* type for commands the FC
//! generates itself (failsafe / autoland). It is trusted by construction
//! but deliberately not a [`super::VerifiedSystemCommand`]: an internal
//! failsafe must never masquerade as an externally verified command, and
//! external verification must never be satisfiable by something the FC
//! minted for itself. Minting one requires the [`FailsafeAuthority`]
//! capability, of which at most ONE exists per process.

#[cfg(any(test, feature = "internal-failsafe"))]
use core::sync::atomic::{AtomicBool, Ordering};

use aviate_hal_io::SystemCommand;

/// Tracks whether the process-wide [`FailsafeAuthority`] has been taken.
#[cfg(any(test, feature = "internal-failsafe"))]
static FAILSAFE_AUTHORITY_TAKEN: AtomicBool = AtomicBool::new(false);

/// Capability required to mint a [`TrustedInternalCommand`].
///
/// At most one exists per process: `FailsafeAuthority::take` (gated behind
/// the `internal-failsafe` feature) hands out the value exactly once (the
/// `cortex_m::Peripherals::take()` idiom). The flight assembly takes it at
/// boot and hands it to the failsafe subsystem; any later attempt —
/// including one from a compromised or misconfigured dependency that
/// happens to enable the Cargo feature — gets `None`. A Cargo feature alone
/// would not be an authority boundary: feature unification turns it into a
/// mere availability switch for every crate in the graph, so the singleton,
/// not the feature, carries the authority. The type is deliberately not
/// `Clone`.
#[derive(Debug)]
pub struct FailsafeAuthority {
    _seal: (),
}

impl FailsafeAuthority {
    /// Take the process-wide failsafe minting capability, once.
    ///
    /// Returns `None` on every call after the first. Call it at
    /// failsafe-subsystem construction, before untrusted tasks run, and
    /// thread the value to the code that mints. The `internal-failsafe`
    /// feature prunes the API from assemblies that never mint internal
    /// commands; the once-only semantics are what actually bound the
    /// authority.
    #[cfg(any(test, feature = "internal-failsafe"))]
    pub fn take() -> Option<Self> {
        // The once-flag is pure state (no I/O): swap-true returns the
        // previous value, so exactly one caller observes `false`.
        if FAILSAFE_AUTHORITY_TAKEN.swap(true, Ordering::AcqRel) {
            None
        } else {
            Some(Self { _seal: () })
        }
    }
}

/// A command generated by the FC itself (failsafe, autoland).
///
/// Trusted because the FC minted it, but intentionally NOT a
/// [`super::VerifiedSystemCommand`]: it never refreshes external-source
/// freshness and never satisfies an external-authority requirement. The
/// flight-cycle dispatch handles the two on separate paths.
#[derive(Debug, Clone)]
pub struct TrustedInternalCommand {
    command: SystemCommand,
}

impl TrustedInternalCommand {
    /// Mint a self-generated command as trusted-internal.
    ///
    /// Requires a [`FailsafeAuthority`] capability, so only the failsafe
    /// subsystem the assembly granted it to can mint one.
    pub fn mint(command: SystemCommand, _authority: &FailsafeAuthority) -> Self {
        Self { command }
    }

    /// Borrow the internal command.
    pub fn command(&self) -> &SystemCommand {
        &self.command
    }

    /// Consume and yield the internal command for dispatch.
    pub fn into_command(self) -> SystemCommand {
        self.command
    }
}
