//! The untrusted ingress boundary and the internal-command escape hatch.
//!
//! [`UnverifiedSystemCommand`] is what a transport produces after parsing
//! bytes: a candidate command plus the signature material the gateway needs
//! to authenticate it. It carries no proof and cannot reach the flight
//! cycle — the only thing that accepts it is [`super::CommandGateway`].
//!
//! Crucially it does NOT carry a claimed *source* or a claimed *sequence*.
//! Authority and freshness are derived by the gateway from the
//! authenticated signature (its credential identity and its monotonic
//! timestamp), never from fields an attacker could set. See
//! [`super::CommandGateway::admit`].
//!
//! [`TrustedInternalCommand`] is a *distinct* type for commands the FC
//! generates itself (failsafe / autoland). It is trusted by construction
//! but deliberately not a [`super::VerifiedSystemCommand`]: an internal
//! failsafe must never masquerade as an externally verified command, and
//! external verification must never be satisfiable by something the FC
//! minted for itself. Minting one requires a [`FailsafeAuthority`]
//! capability, which the flight assembly grants only to the failsafe
//! subsystem — a public constructor is not provenance.

use aviate_hal_io::SystemCommand;
use aviate_link::command::SignatureMeta;

/// A parsed-but-unverified command from a transport.
///
/// Construction is public — building one is exactly what an untrusted
/// transport is allowed to do. What it cannot do is turn one into a
/// [`super::VerifiedSystemCommand`]; only the gateway can, and only after
/// authenticating the carried signature. The command's authority and
/// freshness come from that authenticated signature, so this type exposes
/// no `source` or `sequence` field to forge.
///
/// `SignatureMeta` already carries the fixed-size frame the HMAC covers, so
/// this type stays allocation-free without a second copy of the bytes.
#[derive(Debug)]
pub struct UnverifiedSystemCommand {
    command: SystemCommand,
    signature: Option<SignatureMeta>,
}

impl UnverifiedSystemCommand {
    /// Build an unverified command from a transport's parse result.
    ///
    /// * `command` — the mapped kernel-facing command (untrusted);
    /// * `signature` — signature metadata (with the signed frame) if the
    ///   frame was signed; `None` for an unsigned frame.
    pub fn new(command: SystemCommand, signature: Option<SignatureMeta>) -> Self {
        Self { command, signature }
    }

    /// Signature metadata (including the signed frame), if signed. This is
    /// the sole authority the gateway trusts: its credential identity binds
    /// the source, its timestamp binds freshness.
    pub fn signature(&self) -> Option<&SignatureMeta> {
        self.signature.as_ref()
    }

    /// Consume and yield the untrusted command. Crate-internal: only the
    /// gateway, at the moment it mints a verified command, takes the
    /// command out — no external code can extract it and skip the check.
    pub(super) fn into_command(self) -> SystemCommand {
        self.command
    }
}

/// Capability required to mint a [`TrustedInternalCommand`].
///
/// The flight assembly constructs exactly one and hands it to the failsafe
/// subsystem; nothing else can mint self-generated commands. In a flight
/// build there is no way to obtain one without the `internal-failsafe`
/// feature, so ambient minting does not compile.
#[derive(Debug)]
pub struct FailsafeAuthority {
    _seal: (),
}

impl FailsafeAuthority {
    /// Acquire the failsafe minting capability.
    ///
    /// Gated so only an assembly that explicitly opts in (the failsafe
    /// subsystem, via the `internal-failsafe` feature) — or this crate's
    /// own tests — can obtain it. Call it once, at failsafe-subsystem
    /// construction, and thread the value to the code that mints.
    #[cfg(any(test, feature = "internal-failsafe"))]
    pub fn acquire() -> Self {
        Self { _seal: () }
    }
}

/// A command generated by the FC itself (failsafe, autoland).
///
/// Trusted because the FC minted it, but intentionally NOT a
/// [`super::VerifiedSystemCommand`]: it never refreshes external-source
/// freshness and never satisfies an external-authority requirement. The
/// flight-cycle dispatch handles the two on separate paths.
#[derive(Debug, Clone)]
pub struct TrustedInternalCommand {
    command: SystemCommand,
}

impl TrustedInternalCommand {
    /// Mint a self-generated command as trusted-internal.
    ///
    /// Requires a [`FailsafeAuthority`] capability, so only the failsafe
    /// subsystem the assembly granted it to can mint one.
    pub fn mint(command: SystemCommand, _authority: &FailsafeAuthority) -> Self {
        Self { command }
    }

    /// Borrow the internal command.
    pub fn command(&self) -> &SystemCommand {
        &self.command
    }

    /// Consume and yield the internal command for dispatch.
    pub fn into_command(self) -> SystemCommand {
        self.command
    }
}
