#!/usr/bin/env python3
"""Generate MAVLink 2 signed golden frames for mavlink_interop.rs.

Uses pymavlink (an independent MAVLink implementation) so the Rust
signature path is checked against a foreign signer, not against itself.
Regenerate with:  python3 gen_golden_vectors.py
and paste the output over the generated block in mavlink_interop.rs.
"""

from pymavlink.dialects.v20 import common as mavlink2

KEY = bytes(range(32))  # 0x00..0x1f — matches TEST_SIGNING_KEY in the test
LINK_ID = 5
T0 = 1_234_567_890  # 10 µs units since the MAVLink signing epoch

ARM_DISARM = 400  # MAV_CMD_COMPONENT_ARM_DISARM


def signed_sender(src_system, src_component, timestamp):
    mav = mavlink2.MAVLink(None, srcSystem=src_system, srcComponent=src_component)
    mav.signing.secret_key = KEY
    mav.signing.sign_outgoing = True
    mav.signing.link_id = LINK_ID
    mav.signing.timestamp = timestamp
    return mav


def command_long(mav, param1):
    msg = mav.command_long_encode(0, 0, ARM_DISARM, 0, param1, 0, 0, 0, 0, 0, 0)
    return msg.pack(mav)


def dump(name, buf, comment):
    print(f"/// {comment}")
    print(f"pub const {name}: &[u8] = &[")
    for i in range(0, len(buf), 12):
        row = ", ".join(f"0x{b:02X}" for b in buf[i : i + 12])
        print(f"    {row},")
    print("];")
    print()


print("// Shared by multiple integration-test crates; not every crate uses")
print("// every vector.")
print("#![allow(dead_code)]")
print()
print("// GENERATED by gen_golden_vectors.py — do not edit by hand.")
print(f"// pymavlink {mavlink2.WIRE_PROTOCOL_VERSION} dialect=common, key=0x00..0x1f,")
print(f"// link_id={LINK_ID}, base timestamp T0={T0} (10 us units).")
print()

mav = signed_sender(1, 1, T0)
arm = command_long(mav, 1.0)
dump(
    "SIGNED_ARM_SYS1_COMP1",
    arm,
    f"COMMAND_LONG ARM (param1=1.0), srcSystem=1, srcComponent=1, signed ts=T0={T0}.",
)

disarm = command_long(mav, 0.0)
dump(
    "SIGNED_DISARM_SYS1_COMP1",
    disarm,
    "COMMAND_LONG DISARM (param1=0.0), same stream, signed ts=T0+1.",
)

mav2 = signed_sender(2, 1, T0 + 50)
imposter = command_long(mav2, 1.0)
dump(
    "SIGNED_ARM_SYS2_COMP1",
    imposter,
    "COMMAND_LONG ARM signed with the SAME key/link_id but srcSystem=2 — "
    "valid signature, unauthorized identity.",
)

print(f"pub const T0: u64 = {T0};")
