//! The checked-in C header must equal what cbindgen generates from
//! the Rust definitions — the C++ plugin compiles against that
//! header, so drift between the two IS the cross-language ABI bug
//! this crate exists to prevent.
//!
//! On mismatch the test prints the freshly generated text; update
//! `include/aviate_xil_contract.h` with it (never edit the header by
//! hand).

#![allow(clippy::expect_used, clippy::panic)]

use std::path::PathBuf;

fn generate() -> String {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("AVIATE_XIL_CONTRACT_H".into()),
        no_includes: true,
        sys_includes: vec!["stdint.h".into(), "stddef.h".into()],
        cpp_compat: true,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        usize_is_size_t: true,
        header: Some(
            "/* Generated by cbindgen from aviate-xil-contract — DO NOT EDIT.\n \
             * Regenerate: cargo test -p aviate-xil-contract header (the\n \
             * failing test prints the fresh text). */"
                .into(),
        ),
        export: cbindgen::ExportConfig {
            include: vec![
                "SharedStateV2".into(),
                "SharedStateHeader".into(),
                "ModelStateBlock".into(),
                "MotorCommandBlock".into(),
                "ControlBlock".into(),
                "LifecycleRequest".into(),
                "FcState".into(),
            ],
            prefix: Some("Aviate".into()),
            ..Default::default()
        },
        enumeration: cbindgen::EnumConfig {
            prefix_with_name: true,
            ..Default::default()
        },
        ..Default::default()
    };
    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .with_parse_deps(false);
    let mut out = Vec::new();
    builder
        .generate()
        .expect("cbindgen must parse the contract crate")
        .write(&mut out);
    String::from_utf8(out).expect("cbindgen output is UTF-8")
}

#[test]
fn checked_in_header_matches_generated() {
    let generated = generate();
    let checked_in = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("include/aviate_xil_contract.h"),
    )
    .expect("include/aviate_xil_contract.h must exist (see this test's docs)");
    // Trailing-newline differences carry no ABI meaning; everything
    // else must match byte-for-byte.
    assert_eq!(
        checked_in.trim_end(),
        generated.trim_end(),
        "include/aviate_xil_contract.h drifted from the Rust layout.\n\
         Replace it with the following generated text:\n\
         ================================================\n{generated}\n\
         ================================================"
    );
}
