/* Generated by cbindgen from aviate-xil-contract — DO NOT EDIT.
 * Regenerate: cargo test -p aviate-xil-contract header (the
 * failing test prints the fresh text). */

#ifndef AVIATE_XIL_CONTRACT_H
#define AVIATE_XIL_CONTRACT_H

#include <stdint.h>
#include <stddef.h>

// First eight bytes of the block: ASCII `AVIATEGZ` big-endian. A
// consumer that attaches to anything else is looking at a foreign
// or torn mapping and must fail closed. (Spelled as a literal so
// cbindgen exports it; the equality with the ASCII bytes is pinned
// by a test.)
#define AviateMAGIC 4708031005397960538

// Layout version of [`SharedStateV2`]. Any layout OR protocol
// change bumps this; consumers reject a mismatch on attach.
//
// v3: payload lanes are explicit `u64` bit patterns (v2 typed them
// `f64`/`double`, which forced both sides to pun a `double*` into a
// `uint64_t*` for atomic access — an object-access/aliasing hazard
// in C++ and a needless cast in Rust). v3 also adds
// `writer_incarnation` and requires the initialisation and reset
// protocols v2 lacked. An installed v2 plugin must NOT be accepted
// by a v3 endpoint: it publishes with the old protocol.
#define AviateLAYOUT_VERSION 3

// Retry budget for [`seqlock_read`]: with a 1 kHz writer a reader
// virtually never observes more than one in-flight write; a bounded
// budget keeps a crashed-mid-write writer (seq stuck odd) from
// hanging the reader forever.
#define AviateSEQLOCK_MAX_RETRIES 16

// Lifecycle actions a session host / harness may request.
enum AviateLifecycleRequest
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // No pending request.
  AviateLifecycleRequest_None = 0,
  // Reset the simulation world (and thereby the FC, via the
  // generation bump).
  AviateLifecycleRequest_Reset = 1,
  // Pause the simulation.
  AviateLifecycleRequest_Stop = 2,
  // Resume the simulation.
  AviateLifecycleRequest_Start = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum AviateLifecycleRequest AviateLifecycleRequest;
#else
typedef uint32_t AviateLifecycleRequest;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Flight-controller lifecycle state published in the control block.
enum AviateFcState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // FC process starting; kernel not yet constructed.
  AviateFcState_Init = 0,
  // Reset observed; kernel being reconstructed.
  AviateFcState_Resetting = 1,
  // Kernel constructed; estimator converging on fresh sensors.
  AviateFcState_Converging = 2,
  // Estimator healthy; safe for a consumer to resume.
  AviateFcState_Ready = 3,
  // FC deliberately stopped.
  AviateFcState_Stopped = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum AviateFcState AviateFcState;
#else
typedef uint32_t AviateFcState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Self-describing block header. Writer: gz plugin.
typedef struct AviateSharedStateHeader {
  // [`MAGIC`].
  uint64_t magic;
  // [`LAYOUT_VERSION`].
  uint32_t layout_version;
  // `size_of::<SharedStateV2>()` as the writer compiled it.
  // Consumers compare against their own expectation — see
  // [`validate_attach`] for the macOS page-rounding rule.
  uint32_t declared_size;
  // Simulation-world epoch: 1 on plugin configure, +1 on every
  // world reset. A consumer that sees this change re-establishes
  // its freshness tracking instead of quarantining the source —
  // the "telemetry dies after reset" fix.
  uint32_t reset_generation;
  // Non-zero while the plugin owns the mapping.
  uint32_t plugin_ready;
  // Monotonic identity stamped once per created object: the
  // value the writer's lease grant advanced the counter in the
  // lease file's first 8 bytes (little-endian) to. Each grant
  // applies `wrapping_add(1)` and skips zero — zero is reserved
  // for "not stamped" — under the exclusive lock, and persists
  // the value BEFORE any block carries it, so a writer that dies
  // between grant and stamp merely burns a number and two
  // writers can never share one. Identity is compared for
  // equality only; the counter wraps.
  //
  // This is how a consumer detects a writer that CRASHED and
  // re-created the block: the crashed writer never cleared
  // `plugin_ready`, and the orphaned object stays alive as long
  // as anyone maps it, so the stale mapping keeps serving the
  // dead world's last snapshot and looks perfectly healthy. The
  // consumer must therefore compare the incarnation of the object
  // the NAME resolves to now against the one it attached to —
  // POSIX shm cannot be told apart by inode (macOS reports
  // `st_dev = st_ino = 0` for every shm object).
  //
  // OBJECT-RECREATION VS EPOCH-BUMP is a contract, not an
  // accident of implementation:
  //
  // * A writer (re)start CREATES a new object — new incarnation,
  //   `reset_generation` back at 1. Consumers observe `Replaced`
  //   and must re-attach.
  // * A world reset bumps `reset_generation` IN PLACE — same
  //   object, same incarnation, same mappings. Consumers re-key
  //   their freshness tracking and keep their attachment.
  //
  // LIVENESS is carried outside the block, per incarnation. The
  // writer holds two exclusive advisory locks for its whole life,
  // both released by the kernel on ANY exit including a crash —
  // in-block flags cannot prove a writer is alive, precisely
  // because they survive it:
  //
  // * the GLOBAL lease (`/tmp/<shm name without leading
  //   slash>.lease` — e.g. `/tmp/aviate_gz_bridge.lease`), whose
  //   first 8 bytes hold this counter and which enforces
  //   single-writer ownership: a second writer must fail to take
  //   over an actively held name rather than unlink a live
  //   peer's object. This file is never unlinked (removing a
  //   lock file races its next locker).
  // * the incarnation TOKEN (the global lease path with the
  //   incarnation appended — e.g.
  //   `/tmp/aviate_gz_bridge.lease.7`), locked by the grant
  //   BEFORE the value can reach any block header. "Is the
  //   writer that stamped THIS field alive?" is answered by
  //   probing the token alone. The global lease can never vouch
  //   for a corpse: between a successor's grant and its object
  //   creation the name still resolves to the predecessor's
  //   block while the global lease is genuinely held — and the
  //   counter on file is still the predecessor's until the
  //   successor's write lands — so any verdict built on it
  //   revives the corpse. No grant ever touches another writer's
  //   token. A successor unlinks its predecessor's token file:
  //   the value is never granted twice, and a probe racing the
  //   unlink reads "unlocked", the verdict the unlink preserves.
  uint64_t writer_incarnation;
  // Reserved; zero. Pads the header to a full 64-byte cache-line
  // block: each block of this layout is written by exactly one
  // process, and no two writers ever share a line.
  uint64_t _reserved0[4];
} AviateSharedStateHeader;

// Ground-truth model state. Writer: gz plugin, under `seq`.
//
// `sim_step` and `time_us` live INSIDE the seqlock payload so a
// reader obtains a coherent `{step, time, state}` snapshot in one
// consistent read — the authority for aligning telemetry to sim
// time under acceleration.
typedef struct AviateModelStateBlock {
  // Seqlock: odd while the plugin is writing. Readers retry on
  // odd or changed values (see [`crate::seqlock_read`]).
  uint32_t seq;
  // The simulation-world epoch this snapshot belongs to —
  // mirrors the header's `reset_generation` INSIDE the seqlock
  // payload, so a consumer's `{generation, step, time, state}`
  // quadruple is coherent in one read and a snapshot can never
  // be attributed to the wrong epoch across a reset.
  uint32_t reset_generation;
  // Physics step counter. Monotonic across world resets — epochs
  // are distinguished by `reset_generation`, not by this counter
  // restarting.
  uint64_t sim_step;
  // Simulation time (µs). Rewinds to zero on a world reset.
  uint64_t time_us;
  // Position (m), world ENU — IEEE-754 `f64` BIT PATTERNS.
  //
  // Every payload lane is a `u64` on the wire, not a `double`.
  // Both sides access lanes atomically, and typing them as
  // integers means neither side has to pun a `double*` into a
  // `uint64_t*` to do it: that pun is an object-access /
  // strict-aliasing hazard in C++ and an avoidable cast in Rust.
  // Convert at the boundary (`f64::from_bits` / `memcpy`), never
  // in the middle.
  uint64_t pos_bits[3];
  // Orientation quaternion [w, x, y, z], ENU-world / FLU-body —
  // `f64` bit patterns (see [`Self::pos_bits`]).
  uint64_t quat_bits[4];
  // Linear velocity [m/s], world ENU — `f64` bit patterns.
  uint64_t vel_bits[3];
  // Angular velocity [rad/s] in the WORLD ENU frame — gz's
  // `WorldAngularVelocity` component verbatim, not a body-frame
  // gyro.
  //
  // Known unreliable: the component reports zero on this setup
  // even while the attitude quaternion shows sustained rotation,
  // so the X500 FC does not use it — `synthesize.rs` derives body
  // rates from successive `quat` samples instead. Treat this lane
  // as advisory until a consumer proves the component's fidelity.
  uint64_t ang_vel_bits[3];
  // Non-zero once the first physics step has been published.
  uint32_t valid;
  // Padding; zero.
  uint32_t _pad1;
  // Reserved; zero. Pads the block to a 64-byte cache-line
  // multiple so the FC-written command block never shares a line
  // with this plugin-written block.
  uint64_t _reserved_state[7];
} AviateModelStateBlock;

// Motor command. Writer: flight controller, under `seq`.
typedef struct AviateMotorCommandBlock {
  // Seqlock: odd while the FC is writing.
  uint32_t seq;
  // Number of populated `motor_vel` lanes.
  uint32_t num_motors;
  // Rotor angular-velocity setpoints [rad/s] as `f64` bit
  // patterns (see [`ModelStateBlock::pos_bits`]). The FC applies
  // the resolved actuator curve BEFORE writing — values here are
  // boundary commands, never force-domain thrust.
  uint64_t motor_vel_bits[8];
  // Last `sim_step` the FC finished processing. Doubles as the FC
  // liveness heartbeat and as the lockstep acknowledgement the
  // plugin blocks on. Accessed as a bare aligned atomic, OUTSIDE
  // the seqlock payload: the FC acks every step even on cycles
  // that publish no new motor values, and a monotonic u64 needs
  // no tear protection.
  uint64_t fc_step_ack;
  // Reserved; zero. Pads the block to a 64-byte cache-line
  // multiple (see `_reserved_state`).
  uint64_t _reserved1[6];
} AviateMotorCommandBlock;

// Runtime control plane. Field-per-owner; every field is a
// single naturally-aligned word accessed atomically. Compound pairs
// that must be read consistently — `(nonce, request)` and
// `(generation, state)` — are PACKED into one `u64` each, so no
// reader can pair a fresh nonce with a stale request word or
// `Ready` with a stale generation — typed coherent snapshots,
// not hidden read-order conventions.
typedef struct AviateControlBlock {
  // Packed lifecycle request: high 32 bits = request nonce, low
  // 32 bits = [`LifecycleRequest`] word (see
  // [`pack_lifecycle_request`]). One atomic word = one coherent
  // request. Writer: session host / harness (single requester;
  // nonce comparison is equality-based, so wrapping is safe).
  uint64_t lifecycle_request;
  // Set by the PLUGIN to the request nonce once the simulator
  // has ACCEPTED the action (service success) — the "ack" half
  // of request → ack → ready. A request whose nonce equals this
  // value is complete or duplicate; the executor never re-runs
  // it.
  uint32_t lifecycle_ack_nonce;
  // FC session identity, owned by the FC endpoint: each FC
  // attachment stamps the previous value advanced by
  // `wrapping_add(1)` with zero skipped — zero means no FC has
  // ever attached to this object (a fresh object resets it).
  // Watchers detect an FC restart or re-attach by comparing for
  // equality only; the counter wraps and its ordering carries no
  // meaning across a writer restart. Writer: FC.
  uint32_t fc_session_nonce;
  // Packed FC status: high 32 bits = the `reset_generation` the
  // state refers to, low 32 bits = [`FcState`] word (see
  // [`pack_fc_status`]). One atomic word, so `Ready` can never
  // be observed with a stale generation. `Ready` counts only
  // when the packed generation equals the header's current
  // `reset_generation`. Writer: FC.
  uint64_t fc_status;
  // Runtime lockstep toggle: non-zero = the plugin blocks each
  // physics step on `fc_step_ack`; runtime-writable, not a
  // load-time SDF constant. Writer: session host / harness.
  uint32_t lockstep_enabled;
  // Target real-time factor in percent: 100 = 1×, 400 = 4×,
  // 0 = as-fast-as-possible. The plugin forwards changes to the
  // physics engine. Writer: session host / harness.
  uint32_t target_rtf_percent;
  // Reserved; zero. Pads the block to a full cache line. The
  // control words are event-rate, so the mixed host/FC writers
  // inside this one line are deliberate; the HIGH-RATE state and
  // command blocks are the ones that must never share a line
  // across processes.
  uint32_t _reserved2[8];
} AviateControlBlock;

// The full version-2 shared block.
typedef struct AviateSharedStateV2 {
  // Self-describing header.
  struct AviateSharedStateHeader header;
  // Ground-truth model state (plugin → FC/consumers).
  struct AviateModelStateBlock state;
  // Motor command (FC → plugin).
  struct AviateMotorCommandBlock command;
  // Runtime control plane.
  struct AviateControlBlock control;
} AviateSharedStateV2;

#endif  /* AVIATE_XIL_CONTRACT_H */

