/* Generated by cbindgen from aviate-xil-contract — DO NOT EDIT.
 * Regenerate: cargo test -p aviate-xil-contract header (the
 * failing test prints the fresh text). */

#ifndef AVIATE_XIL_CONTRACT_H
#define AVIATE_XIL_CONTRACT_H

#include <stdint.h>
#include <stddef.h>

// First eight bytes of the block: ASCII `AVIATEGZ` big-endian. A
// consumer that attaches to anything else is looking at a foreign
// or torn mapping and must fail closed. (Spelled as a literal so
// cbindgen exports it; the equality with the ASCII bytes is pinned
// by a test.)
#define AviateMAGIC 4708031005397960538

// Layout version of [`SharedStateV2`]. Any layout change bumps this;
// consumers reject a mismatch on attach.
#define AviateLAYOUT_VERSION 2

// Retry budget for [`seqlock_read`]: with a 1 kHz writer a reader
// virtually never observes more than one in-flight write; a bounded
// budget keeps a crashed-mid-write writer (seq stuck odd) from
// hanging the reader forever.
#define AviateSEQLOCK_MAX_RETRIES 16

// Lifecycle actions a session host / harness may request (#265).
enum AviateLifecycleRequest
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // No pending request.
  AviateLifecycleRequest_None = 0,
  // Reset the simulation world (and thereby the FC, via the
  // generation bump).
  AviateLifecycleRequest_Reset = 1,
  // Pause the simulation.
  AviateLifecycleRequest_Stop = 2,
  // Resume the simulation.
  AviateLifecycleRequest_Start = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum AviateLifecycleRequest AviateLifecycleRequest;
#else
typedef uint32_t AviateLifecycleRequest;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Flight-controller lifecycle state published in the control block.
enum AviateFcState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // FC process starting; kernel not yet constructed.
  AviateFcState_Init = 0,
  // Reset observed; kernel being reconstructed.
  AviateFcState_Resetting = 1,
  // Kernel constructed; estimator converging on fresh sensors.
  AviateFcState_Converging = 2,
  // Estimator healthy; safe for a consumer to resume.
  AviateFcState_Ready = 3,
  // FC deliberately stopped.
  AviateFcState_Stopped = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum AviateFcState AviateFcState;
#else
typedef uint32_t AviateFcState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Self-describing block header. Writer: gz plugin.
typedef struct AviateSharedStateHeader {
  // [`MAGIC`].
  uint64_t magic;
  // [`LAYOUT_VERSION`].
  uint32_t layout_version;
  // `size_of::<SharedStateV2>()` as the writer compiled it.
  // Consumers compare against their own expectation — see
  // [`validate_attach`] for the macOS page-rounding rule.
  uint32_t declared_size;
  // Simulation-world epoch: 1 on plugin configure, +1 on every
  // world reset. A consumer that sees this change re-establishes
  // its freshness tracking instead of quarantining the source —
  // the "telemetry dies after reset" fix (#265).
  uint32_t reset_generation;
  // Non-zero while the plugin owns the mapping.
  uint32_t plugin_ready;
  // Reserved; zero.
  uint64_t _reserved0;
} AviateSharedStateHeader;

// Ground-truth model state. Writer: gz plugin, under `seq`.
//
// `sim_step` and `time_us` live INSIDE the seqlock payload so a
// reader obtains a coherent `{step, time, state}` snapshot in one
// consistent read — the authority for aligning telemetry to sim
// time under acceleration (#265).
typedef struct AviateModelStateBlock {
  // Seqlock: odd while the plugin is writing. Readers retry on
  // odd or changed values (see [`crate::seqlock_read`]).
  uint32_t seq;
  // Padding; zero.
  uint32_t _pad0;
  // Physics step counter. Monotonic across world resets — epochs
  // are distinguished by `reset_generation`, not by this counter
  // restarting.
  uint64_t sim_step;
  // Simulation time (µs). Rewinds to zero on a world reset.
  uint64_t time_us;
  // Position (m), world ENU.
  double pos[3];
  // Orientation quaternion [w, x, y, z], ENU-world / FLU-body.
  double quat[4];
  // Linear velocity [m/s], world ENU.
  double vel[3];
  // Angular velocity [rad/s], body FLU.
  double ang_vel[3];
  // Non-zero once the first physics step has been published.
  uint32_t valid;
  // Padding; zero.
  uint32_t _pad1;
} AviateModelStateBlock;

// Motor command. Writer: flight controller, under `seq`.
typedef struct AviateMotorCommandBlock {
  // Seqlock: odd while the FC is writing.
  uint32_t seq;
  // Number of populated `motor_vel` lanes.
  uint32_t num_motors;
  // Rotor angular-velocity setpoints [rad/s]. The FC applies the
  // resolved actuator curve BEFORE writing — values here are
  // boundary commands, never force-domain thrust (#140).
  double motor_vel[8];
  // Last `sim_step` the FC finished processing. Doubles as the FC
  // liveness heartbeat and as the lockstep acknowledgement the
  // plugin blocks on. Accessed as a bare aligned atomic, OUTSIDE
  // the seqlock payload: the FC acks every step even on cycles
  // that publish no new motor values, and a monotonic u64 needs
  // no tear protection.
  uint64_t fc_step_ack;
  // Reserved; zero.
  uint64_t _reserved1;
} AviateMotorCommandBlock;

// Runtime control plane (#265). Field-per-owner; every field is one
// naturally-aligned `u32` accessed atomically.
typedef struct AviateControlBlock {
  // Requested lifecycle action ([`LifecycleRequest`] as u32).
  // Writer: session host / harness.
  uint32_t lifecycle_request;
  // Bumped by the requester with every new request; the request
  // is `(lifecycle_request, lifecycle_request_nonce)`.
  uint32_t lifecycle_request_nonce;
  // Set by the PLUGIN to the request nonce once the action has
  // been forwarded to the simulator — the "ack" half of
  // request → ack → ready.
  uint32_t lifecycle_ack_nonce;
  // Flight-controller lifecycle state ([`FcState`] as u32) — the
  // "ready" half of request → ack → ready. Writer: FC.
  uint32_t fc_state;
  // The `reset_generation` that `fc_state` refers to. `Ready`
  // only counts when this equals the header's current generation.
  // Writer: FC.
  uint32_t fc_state_generation;
  // Written once per FC process start (any non-repeating value);
  // consumers detect an FC restart by a change here even though
  // the shm object identity is unchanged. Writer: FC.
  uint32_t fc_session_nonce;
  // Runtime lockstep toggle: non-zero = the plugin blocks each
  // physics step on `fc_step_ack` (#265 — no longer load-time
  // SDF-only). Writer: session host / harness.
  uint32_t lockstep_enabled;
  // Target real-time factor in percent: 100 = 1×, 400 = 4×,
  // 0 = as-fast-as-possible. The plugin forwards changes to the
  // physics engine. Writer: session host / harness.
  uint32_t target_rtf_percent;
  // Reserved; zero.
  uint32_t _reserved2[4];
} AviateControlBlock;

// The full version-2 shared block.
typedef struct AviateSharedStateV2 {
  // Self-describing header.
  struct AviateSharedStateHeader header;
  // Ground-truth model state (plugin → FC/consumers).
  struct AviateModelStateBlock state;
  // Motor command (FC → plugin).
  struct AviateMotorCommandBlock command;
  // Runtime control plane.
  struct AviateControlBlock control;
} AviateSharedStateV2;

#endif  /* AVIATE_XIL_CONTRACT_H */

