[package]
license.workspace = true
publish = false  # internal crate — not released to crates.io
name = "aviate-app-sitl-xplane-alia250-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
aviate-config = { path = "../../../aviate-config" }
aviate-core = { path = "../../../aviate-core" }
aviate-hal-xil = { path = "../../../aviate-hal/xil" }
aviate-runtime = { path = "../../../aviate-runtime", features = ["env-sitl"] }

[lints]
workspace = true
